command:
  - uvicorn
  - backend.main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: CATALOG
    value: "aamruthcatalog"
  - name: SCHEMA
    value: "retrieval_studio"
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/endpoints/cb1143f131bd6e99"
  - name: BUILD_NOTEBOOK_PATH
    value: "/Workspace/Users/amruth.ashok@databricks.com/retrieval-studio/retrieval-studio/notebooks/build_notebook_v2"
  - name: EVAL_NOTEBOOK_PATH
    value: "/Workspace/Users/amruth.ashok@databricks.com/retrieval-studio/retrieval-studio/notebooks/eval_notebook"
